### ISSUE TITLE
Inference Example

### ISSUE THREAD

**Issue by aymen-mouelhi** [shchur/triangular-tpp#1]
Hello Oleksandr,
Thank you very much for sharing the code of this interesting method as well as all other TPP repos and blogs you're writing.
Can you please share an example of inference and events simulation/generation using the estimated density ?
Thanks !

**Comment by shchur** [comment]
Thank you Aymen! You should be able generate event sequences from a trained model (training described in [this script](https://github.com/shchur/triangular-tpp/blob/main/scripts/experiment.py)) as follows:
```python
t_raw = model.rsample(batch_size=32)
t, mask = model.clip_times(t_raw)
```
This code will generate `batch_size=32` event sequences from the interval `[0, model.t_max]`. In this result `t` will contain the padded arrival times and `mask` will be a binary mask indicating which entries of `t` correspond to actually observed events (not padding).

**Comment by aymen-mouelhi** [comment]
Thank you so much for your help ! truly appreciate it !
