### ISSUE TITLE
Queries about RNN benchmark

### ISSUE THREAD

**Issue by gzagatti** [shchur/triangular-tpp#2]
@shchur thanks for sharing the code with the rest of the community. The code is very well structured and commented which is great help.

I would like to clarify your RNN implementation. In the paper you cited a few RNN models. However, the [RNN model in the source code](https://github.com/shchur/triangular-tpp/blob/main/ttpp/models.py#L64) seems to use a different architecture. Using the same notation that you used in the appendix of your paper, the transformation you implemented is $F = \psi^{-1} \circ G_{RNN} \circ \psi \circ \frac{\lambda}{T} I \circ D$, where $G_{RNN}$ is a spline whose parameters are computed sequentially via a $RNN$.

On the other hand, the other papers you cited like Du et al. (2016) use the RNN slightly different in that they model the intensity function itself as an RNN. In the language of your model, that would be $F = H \circ RNN$ where $H$ is a function of the RNN output like the Gompertz CDF.

Are both formulations equivalent? My understanding is that they are not since you add a spline layer to the output of each RNN hidden cell while the other methods just use the vanilla RNN. Is that right? Is there any reason why you decided to couple the spline to the RNN architecture rather than performing a direct comparison with previous methods?

**Comment by shchur** [comment]
Hi, thanks for the question! The only difference between the RNN in Du et al. and the baseline in our work is how they parametrize the conditional distribution of the next inter-event time. 
- In RMTPP, they choose a simple parametric form for the conditional hazard function (Eq. 11 in their paper)
- In our work, the conditional distribution is parametrized using a spline. This is very similar to [this work](https://proceedings.mlr.press/v151/ben-taieb22a.html) that studies such a spline-based parametrization in more detail. According to their experiments, using spline leads to much better results that the simple 2-parameter parametrization from RMTPP (see Tables 1 & 2).

We chose to use splines here to make the proposed model (TriTPP) as comparable as possible with the RNN. The RNN model is very similar to the renewal process model $F = C \circ \Phi_2 \circ D$, where we model the inter-event time distribution with a spline. 
- in the renewal process we use the spline with the same fixed parameters for each inter-event time (i.e., parameters of the spline don't depend on history)
- in the RNN, the parameters of the spline are obtained from the RNN hidden state, and therefore are history-dependent

**Comment by gzagatti** [comment]
Perfect! Thanks very much for your super fast and informative answer. It is now much clear how you handled the RNN baseline in your paper. Great work!
